### ISSUE TITLE
RynoOGG: 201.150.55.119 123 TTI Source Lane, 10001 New York

### ISSUE THREAD

**Issue by rynogg** [itsinfinity/RTTIMSRC#1]
I put my whole life into this source code. Yes  it may be stolen from TTI, but hey! I worked hard on it :(?

**Comment by rynogg** [comment]
also to point out im a novice programmer so idk why you're claiming this leak as an accomplishment

**Comment by toonjoey** [comment]
Hilarious how you make it sooo "private" yet it's easily leaked.

**Comment by itsinfinity** [comment]
Your ToonImport.pyc is no match to my Decompiler.

**Comment by toonjoey** [comment]
A decompiler that's found easily no less.

**Comment by toonjoey** [comment]
Also somehow you don't want it leaked, and (yet again) you make it easy to find.

**Comment by itsinfinity** [comment]
@rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg

**Comment by itsinfinity** [comment]
Also, i dont have a ex, 👍  Dox coming soon.

**Comment by itsinfinity** [comment]
Reopened as i have obtained his IP.

**Comment by toonjoey** [comment]
OOF INTENSIFIES
